### ISSUE TITLE
Right | folder permissions | osx | >>> cannot overwrite non-directory '/bitnami/prestashop/./licenses' with directory './licenses'

### ISSUE THREAD

**Issue by adrienpsl** [bitnami/bitnami-docker-prestashop#101]
**Description**

Hello,

My first installation can't finish, I get these logs:
```shell
prestashop_1  | prestashop 06:45:37.27 INFO  ==> Running install script
prestashop_1  | prestashop 06:47:14.14 INFO  ==> Updating store settings
prestashop_1  | prestashop 06:47:14.39 INFO  ==> Persisting PrestaShop installation
prestashop_1  | cp: cannot overwrite non-directory '/bitnami/prestashop/./licenses' with directory './licenses'
test-docker_prestashop_1 exited with code 1
```

If I restart the container everything works fine.
I'm on osx lastest version, intel

Here my docker-compose:
```yml
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
    ports:
      - '3306:3306'
    volumes:
      - ./db:/bitnami/mariadb
  prestashop:
    image: 'docker.io/bitnami/prestashop:latest'
    user: root
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_DATABASE_HOST=mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./prestashop:/bitnami/prestashop
    depends_on:
      - mariadb
```

Thank you for your help :).

**Comment by alvneiayu** [comment]
hi @adrienpsl 

It seems that it is a permission problem in your folders (db and prestashop). Take a look this section:

[Mount host directories as data volumes with Docker Compose](https://github.com/bitnami/bitnami-docker-prestashop#mount-host-directories-as-data-volumes-with-docker-compose)

```
 NOTE: As this is a non-root container, the mounted files and directories must have the proper permissions for the UID 1001
 ```

I think that doing this, you will fix your problem without problem. Let me know If you still have problems.

Thanks a lot

Álvaro

**Comment by adrienpsl** [comment]
hi @alvneiayu :).

Thanks for your reply.

On my first try, according to [work-with-non-root-containers](https://docs.bitnami.com/tutorials/work-with-non-root-containers/) at the paragraph:  `Using Non-Root Containers as Root Containers`, 
I have set my user as root in the docker-compose.yml:
```yml
  prestashop:
    image: 'docker.io/bitnami/prestashop:latest'
    user: root
```
I thought it would work, but it didn't :).

I've follow your link and did these commands:
```bash
mkdir prestashop
sudo chown 1001 prestashop
docker-compose up
```

This time I was unable to finish the installation:
```bash
prestashop_1  | chmod: changing permissions of '/bitnami/prestashop': Operation not permitted
```
