### ISSUE TITLE
Instance keep redirecting to localhost while using Nginx as reverse proxy

### ISSUE THREAD

**Issue by huzaynbolt** [bitnami/bitnami-docker-prestashop#110]
**Description**

Accessing the Installed service via the Host URL keeps redirecting to localhost. 
I set up an instance that can be accessed on port 8084 in the container host, I then create an Nginx redirection, that forwards request from zzz.yyy.xxx to that port. 

**Describe the results you received:**

While accessing zzz.yyy.xxx via the browser, it keeps redirecting to http://localhost

**Describe the results you expected:**

I should be redirected to the instance running and the URL shouldn't change to localhost

- Output of `docker-compose version` (if applicable):

```
version: '2'
services:
  mariadb_pshp:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
    volumes:
      - 'mariadb_pshp_data:/bitnami/mariadb'
  prestashop:
    image: docker.io/bitnami/prestashop:1.7
    ports:
      - '8084:8080'
    environment:
      - PRESTASHOP_HOST=zzz.yyy.xxx
      - PRESTASHOP_DATABASE_HOST=mariadb_pshp
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'prestashop_pshp_data:/bitnami/prestashop'
    depends_on:
      - mariadb_pshp
volumes:
  mariadb_pshp_data:
    driver: local
  prestashop_pshp_data:
    driver: local


```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Nginx -Reverse proxy on Port 8084
