### ISSUE TITLE
Can't Access Admin Page Using Nginx Reverse Proxy

### ISSUE THREAD

**Issue by huzaynbolt** [bitnami/bitnami-docker-prestashop#111]
**Description**

I was able setup a Prestashop instance via the Docker Compse workflow, Set the PRESTAHOP_HOST variable to a domain name.  The domain was then used as a reverse proxy to the container. 

**Steps to reproduce the issue:**

1. Run Prestashop instance via Docker compose
2. Setup Nginx Proxy using a sample command below where 8084 is the mapped port for the Prestashop instance
```
 server {
   listen 80;
   server_name prestashop.xyz.zzz;

   location /  {
   proxy_set_header Host $host;
   proxy_pass http://127.0.0.1:8084;
   proxy_redirect off;
  }
}
```


3. Try to access the Admin page via prestashop.xyz.zzz/administration

**Describe the results you received:**
I was redirected to prestashop.xyz.zzz:8080/administration/, which makes the site inaccessible.

**Describe the results you expected:**

I expected the redirection to retain the URL format and not add the 8080 port to it. 

**Additional information you deem important (e.g. issue happens only occasionally):**



```
version: '2'                                                                                 
services:                                                                                    
  mariadb_pshp:                                                                              
    image: docker.io/bitnami/mariadb:10.3                                                    
    environment:                                                                             
      - ALLOW_EMPTY_PASSWORD=yes                                                             
      - MARIADB_USER=bn_prestashop                                                           
      - MARIADB_DATABASE=bitnami_prestashop                                                  
    volumes:                                                                                 
      - 'mariadb_pshp_data:/bitnami/mariadb'                                                 
  prestashop:                                                                                
    image: docker.io/bitnami/prestashop:1.7                                                  
    ports:                                                                                   
      - '8084:8080'                                                                          
    environment:                                                                             
      - PRESTASHOP_HOST=prestashop.xyz.zzz                                     
      - PRESTASHOP_EXTERNAL_HTTP_PORT_NUMBER=8084                                            
      - PRESTASHOP_DATABASE_HOST=mariadb_pshp                                                
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306                                                 
    .............                                                         
    volumes:                                                                                 
      - 'prestashop_pshp_data:/bitnami/prestashop'                                           
    depends_on:                                                                              
      - mariadb_pshp                                                                         
volumes:                                                                                     
  mariadb_pshp_data:                                                                         
    driver: local                                                                            
  prestashop_pshp_data:                                                                      
    driver: local                                                                            
                                                                                             
                             
```                                                                
                                                                                             `

**Comment by alvneiayu** [comment]
hi @huzaynbolt

Let me reproduce the issue. I will come back with some feedback as soon as possible.

Thanks

Álvaro

**Comment by alvneiayu** [comment]
hi @huzaynbolt 

First of all, thanks a lot for reporting the problem. I can reproduce an issue setting up the external port in Prestashop.

I created an internal task to solve the issue and added it to the backlog. I am not able to give you an ETA. We will update this thread once we have news.

Thanks a lot

Álvaro

**Comment by huzaynbolt** [comment]
Thanks, @alvneiayu . I'll await the feedback

**Comment by beltran-rubo** [comment]
Hi @huzaynbolt 

The PRESTASHOP_EXTERNAL_HTTP_PORT_NUMBER variable is to configure Prestshop with the port that the user would see, in your case should be '80' that is the default one. You should remove that from your docker-compose file.

I tested a docker-compose with a domain and it works properly. Please make sure you delete the volumes before changing that configuration, the domain and port is something configured at the installation time of the application and if you modify you would need to start the docker-compose without any previous data.


```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  prestashop:
    image: docker.io/bitnami/prestashop:1.7
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - PRESTASHOP_HOST=example.com
      - PRESTASHOP_DATABASE_HOST=mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'prestashop_data:/bitnami/prestashop'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
```

I hope it helps
