### ISSUE TITLE
docker compose not work

### ISSUE THREAD

**Issue by donnyatabitech** [bitnami/bitnami-docker-prestashop#115]
```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.4
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
    ports:
      - '3308:3308'
    volumes:
      - './volumes/mariadb_data:/bitnami/mariadb'
  prestashop:
    image: docker.io/bitnami/prestashop:1.7
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_DATABASE_HOST=mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './volumes/prestashop_data:/bitnami/prestashop'
    depends_on:
      - mariadb
```
in `volumes` creates two folder `mariadb_data` and `prestashop_data`,, but only `mariadb_data` folder that not empty. what I missing so `prestashop_data` folder empty?
