### ISSUE TITLE
/opt/bitnami/scripts/libprestashop.sh: line 277: 1: missing database host

### ISSUE THREAD

**Issue by tarekzemmouri** [bitnami/bitnami-docker-prestashop#117]
### Name and Version

docker.io/bitnami/prestashop:1.7

### What steps will reproduce the bug?

1- just got the bitnami/prestashop image from hub.docker into my docker-compose.yml file and execute it with a persistant files in local.

### What is the expected behavior?

Prestashop starting normaly

### What do you see instead?
```
prestashop 09:55:57.74 
prestashop 09:55:57.80 Welcome to the Bitnami prestashop container
prestashop 09:55:57.80 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-prestashop
prestashop 09:55:57.80 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-prestashop/issues
prestashop 09:55:57.81 
prestashop 09:55:57.81 INFO  ==> ** Starting PrestaShop setup **
prestashop 09:55:57.91 DEBUG ==> Validating settings in APACHE_* environment variables
realpath: /bitnami/apache/conf: No such file or directory
prestashop 09:55:58.82 INFO  ==> Configuring PHP options
prestashop 09:55:58.98 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
prestashop 09:55:59.07 DEBUG ==> Validating settings in PRESTASHOP_* environment variables...
prestashop 09:55:59.41 INFO  ==> Restoring persisted PrestaShop installation
prestashop 09:56:02.38 INFO  ==> Trying to connect to the database server
prestashop 09:56:02.39 DEBUG ==> Getting database_host from PrestaShop configuration
prestashop 09:56:02.40 DEBUG ==> ^\s*(//\s*)?['"]?database_host['"]?\s*=>?([^;,]+)[;,]
grep: /opt/bitnami/prestashop/app/config/parameters.php: No such file or directory
prestashop 09:56:02.44 DEBUG ==> Getting database_port from PrestaShop configuration
prestashop 09:56:02.51 DEBUG ==> ^\s*(//\s*)?['"]?database_port['"]?\s*=>?([^;,]+)[;,]
grep: /opt/bitnami/prestashop/app/config/parameters.php: No such file or directory
prestashop 09:56:02.55 DEBUG ==> Getting database_name from PrestaShop configuration
prestashop 09:56:02.57 DEBUG ==> ^\s*(//\s*)?['"]?database_name['"]?\s*=>?([^;,]+)[;,]
grep: /opt/bitnami/prestashop/app/config/parameters.php: No such file or directory
prestashop 09:56:02.59 DEBUG ==> Getting database_user from PrestaShop configuration
prestashop 09:56:02.60 DEBUG ==> ^\s*(//\s*)?['"]?database_user['"]?\s*=>?([^;,]+)[;,]
grep: /opt/bitnami/prestashop/app/config/parameters.php: No such file or directory
prestashop 09:56:02.62 DEBUG ==> Getting database_password from PrestaShop configuration
prestashop 09:56:02.63 DEBUG ==> ^\s*(//\s*)?['"]?database_password['"]?\s*=>?([^;,]+)[;,]
grep: /opt/bitnami/prestashop/app/config/parameters.php: No such file or directory
/opt/bitnami/scripts/libprestashop.sh: line 277: 1: missing database host
```
### Additional information

I share with my docker-compose.yml file, i want to understand what's wrong with it.
```yaml
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.4
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=bitnami_prestashop
      - MARIADB_ROOT_PASSWORD=biopooltech88
      - BITNAMI_DEBUG=true
    networks:
      - app-tier
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
      - './prestashop.sql:/docker-entrypoint-initdb.d/bitnami_prestashop.sql'
  prestashop:
    image: docker.io/bitnami/prestashop:1.7
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_DATABASE_HOST=mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - PRESTASHOP_DATABASE_PASSWORD=biopooltech88
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - BITNAMI_DEBUG=true
    networks:
      - app-tier
    volumes:
      - './path/local/:/bitnami/prestashop'
      - './path/local/modules:/bitnami/prestashop/modules'
      - './path/local/themes:/bitnami/prestashop/themes'
      - './path/local/override:/bitnami/prestashop/override'
      - './path/local/img:/bitnami/prestashop/img'
    depends_on:
      - mariadb
    links:
      - mariadb:mariadb
volumes:
  mariadb_data:
    driver: local
  docker_tarek:
    driver: local
networks:
  app-tier:
    external: true
```
