### ISSUE TITLE
PRESTASHOP_EXTERNAL_HTTP_PORT_NUMBER environment variable seems to be ignored

### ISSUE THREAD

**Issue by NicoWeidmann** [bitnami/bitnami-docker-prestashop#119]
### Name and Version

bitnami/prestashop:1.7

### What steps will reproduce the bug?

1. run `docker-compose up` with following docker-compose.yml:
```yaml
version: '2.4'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  prestashop:
    image: docker.io/bitnami/prestashop:1.7
    ports:
      - '127.0.0.1:8003:8080'
    environment:
      - PRESTASHOP_EXTERNAL_HTTP_PORT_NUMBER=8003
      - PRESTASHOP_DATABASE_HOST=mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'prestashop_data:/bitnami/prestashop'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
```
2. run `curl -Lv http://localhost:8003/administration/` on the host
3. observe curl output: request for `http://localhost:8003/administration/` is redirected to `http://localhost/administration/index.php[...]`, i.e., port 80

### What is the expected behavior?

The `PRESTASHOP_EXTERNAL_HTTP_PORT_NUMBER=8003` should be honored, and the request to `http://localhost:8003/administration/` should be redirected to `http://localhost:8003/administration/index.php[...]`, i.e., the admin login page on port 8003.

### What do you see instead?

`curl -Lv http://localhost:8003/administration/`output is as follows:
```
*   Trying 127.0.0.1:8003...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8003 (#0)
> GET /administration/ HTTP/1.1
> Host: localhost:8003
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< Date: Mon, 09 May 2022 12:52:29 GMT
< Server: Apache
< Set-Cookie: PrestaShop-c76bd2e30bf7a97cca45996a3e0ea935=0; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; HttpOnly; SameSite=Lax
< Set-Cookie: PrestaShop-c76bd2e30bf7a97cca45996a3e0ea935=def50200dec57edbcc464e5ef0298f3dd4219b36a81a6f492570e9e85ddb71ee0354cf4dc740263e1035a9409b7dcf28e3c3755f3fa06345f4d7a9e11fd08dae82ef8c63d193bae198ff08f2975ff03ddf8b21c5616f9ea02014299046ef3de75a596c83243759512ea1baa5b5f37f9387638df156942f6a60d0d6684d900161f366816541cd2d8ab4e4992b1e03dc3c756fdac77096d9e0df4f6b52e6; expires=Sun, 29-May-2022 12:52:29 GMT; Max-Age=1728000; path=/; HttpOnly; SameSite=Lax
< Location: http://localhost/administration/index.php?controller=AdminLogin&token=b9860b720009406f3d155fca31bb8bc9
< Content-Length: 0
< Content-Type: text/html; charset=utf-8
< 
* Connection #0 to host localhost left intact
* Issue another request to this URL: 'http://localhost/administration/index.php?controller=AdminLogin&token=b9860b720009406f3d155fca31bb8bc9'
*   Trying 127.0.0.1:80...
* TCP_NODELAY set
* connect to 127.0.0.1 port 80 failed: Connection refused
* Failed to connect to localhost port 80: Connection refused
* Closing connection 1
curl: (7) Failed to connect to localhost port 80: Connection refused
```

Trying to load `http://localhost:8003/administration/` in a web browser yields an `ERR_CONNECTION_REFUSED`.

### Additional information

As a workaround, it seems to work to set the `PRESTASHOP_HOST` environment variable to `localhost:8003`.
