### ISSUE TITLE
Accessing Prestashop always redirect to localhost

### ISSUE THREAD

**Issue by anzharip** [bitnami/bitnami-docker-prestashop#72]
**Description**

After installing the Prestashop Bitnami docker, the installation run succesfully. Checked the the container run succesfully also. But when accessing the domain, it always redirect to localhost. 

**Steps to reproduce the issue:**

1. Install Prestashop Bitnami following the README. 
2. Configure the Prestashop Hostname in docker-compose.yml. 
3. Run docker-compose up -d
4. Access the hostname configured in the docker-compose.yml. 
5. Address redirected to localhost. 

**Describe the results you received:**

Address redirected to http://localhost. 

**Describe the results you expected:**

It should redirect to the configured domain name. 
**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens consistently. 

**Version**

- Output of `docker version`:

```
(paste your output here)
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:47 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
(paste your output here)
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-38-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 985.2MiB
Name: strapi.dev.pndk.us
ID: OW73:623J:TJ7Z:BIVE:7DR5:KUZT:6VOQ:FCSN:6PDD:K7ZD:NVZO:K3MB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.15rc1
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by anzharip** [comment]
```
ipnet@strapi:~/neohaus-presta$ cat docker-compose.yml
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  prestashop:
    image: 'bitnami/prestashop:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PRESTASHOP_HOST=directus.dev.ipnet.co.id
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      kompose.service.type: nodeport
    ports:
      - '180:80'
      - '1443:443'
    volumes:
      - 'prestashop_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
```

**Comment by anzharip** [comment]
```
➜  ~ curl -v http://directus.dev.ipnet.co.id:180/
*   Trying 103.92.104.204...
* TCP_NODELAY set
* Connected to directus.dev.ipnet.co.id (103.92.104.204) port 180 (#0)
> GET / HTTP/1.1
> Host: directus.dev.ipnet.co.id:180
> User-Agent: curl/7.54.0
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 302 Found
< Date: Fri, 15 Feb 2019 11:47:56 GMT
< Server: Apache/2.4.38 (Unix) OpenSSL/1.1.0j PHP/7.1.26
< X-Powered-By: PHP/7.1.26
< Location: http://localhost/
< Content-Length: 0
< Connection: close
< Content-Type: text/html; charset=utf-8
<
* Closing connection 0
```

**Comment by javsalgar** [comment]
Hi,

Could you confirm that you are not using persisted data? Could you execute `docker-compose down -v` and try again?

**Comment by StyxOfDynamite** [comment]
I'm getting the same behaviour, fresh clone and no persisted data.

**Comment by marcosbc** [comment]
Hi all, it works perfectly for us when using example.com domain. Find our docker-compose.yml file below:

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  prestashop:
    image: 'bitnami/prestashop:1.7'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PRESTASHOP_HOST=example.com
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'prestashop_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
```

Do you find any relevant difference with respect to your docker-compose.yml file?
