### ISSUE TITLE
Stuck at "Your application is being installed, please wait"

### ISSUE THREAD

**Issue by luisnomad** [bitnami/bitnami-docker-prestashop#73]
**Description**

After successfully installing and running Prestashop 1.7, I have restarted docker and now I am stuck at "Your application is being installed, please wait" when I access localhost. I've waited for about 20 minutes and still the same. 

**Steps to reproduce the issue:**

1. docker-compose up
2. docker-compose down
3. docker-compose up

**Describe the results you received:**

Page is stuck at "Your application is being installed, please wait" bitnami message.

**Describe the results you expected:**

The previously installed Prestashop website to work. Everything is persisted (see docker-compose file below), so I don't understand why it says it's installing anything.

**Additional information you deem important (e.g. issue happens only occasionally):**

Running Mac OS Mojave 10.14.3

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

- Output of `docker info`:

```
Containers: 9
 Running: 2
 Paused: 0
 Stopped: 7
Images: 33
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: UOXR:OZVR:MNJ2:44ZM:OOJ7:OT5K:RZ26:BVBQ:SXQZ:FQX7:Z4FG:QHWF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 41
 Goroutines: 65
 System Time: 2019-03-01T15:13:39.6396425Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version`:

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

This is my docker-compose file:

```
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './mariadb_data:/bitnami'
  prestashop:
    image: 'bitnami/prestashop:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './prestashop_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local

```

Thanks!

**Comment by luisnomad** [comment]
This is the output in the console after running `docker-compose up`:

```
prestashop_1  | nami    INFO  Initializing apache
prestashop_1  | apache  INFO  ==> Reconfiguring PID file location...
prestashop_1  | apache  INFO  ==> Configuring dummy certificates...
prestashop_1  | nami    INFO  apache successfully initialized
prestashop_1  | nami    INFO  Initializing php
prestashop_1  | nami    INFO  php successfully initialized
prestashop_1  | nami    INFO  Initializing mysql-client
prestashop_1  | nami    INFO  mysql-client successfully initialized
prestashop_1  | nami    INFO  Initializing libphp
prestashop_1  | nami    INFO  libphp successfully initialized
prestashop_1  | nami    INFO  Initializing prestashop
```

**Comment by javsalgar** [comment]
Hi,

Just to confirm. It seems to me that you are using host path folders (notice that the mounting starts with ./prestashop_data`. Could you remove the `./` in both instances and try again the process?

**Comment by luisnomad** [comment]
Hi @javsalgar, thanks for the comment. I added that because I wanted to be able to access those folders and edit files, do backup, add them to a repo, etc. If I don't mount to these local folders, will I still be able to achieve this? I am quite new to Docker and this seemed to do the job (unless it breaks the whole thing, then it's useless!).

Thanks,

Luis

**Comment by luisnomad** [comment]
So after removing the "./" from the volume paths, I got it working. But then, how can I modify the theme files, add my own modules, backup the database, and so on? I know it's a very newbie question and not really related to your image, but to docker itself. How can we use this bitnami image for development?

Thanks a lot!

**Comment by luisnomad** [comment]
I think what I need is something like this?
```
volumes:
        - type: bind
                source: ./prestashop_data
                target: /bitnami
```
