### ISSUE TITLE
Error executing 'postInstallation' using custom SSL certificates

### ISSUE THREAD

**Issue by Schengatto** [bitnami/bitnami-docker-prestashop#88]
**Description**

I am trying to launch a docker container using the image `bitnami/prestashop:latest`, but if I provide my custom letsencrypt SSL certificates, with names server.crt and server.key, the container wont starts for an `Error executing 'postInstallation': "size" argument must not be negative`

**Steps to reproduce the issue:**

**docker-compose.yml** file.

```
version: '3.1'

services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    restart: always
    environment:
      - MARIADB_USER=test2020
      - MARIADB_PASSWORD=test2020
      - MARIADB_DATABASE=prestashop
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=test
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - 'mariadb_data:/prestashop'
    ports:
      - 13306:3306
  prestashop:
    image: 'bitnami/prestashop:latest'
    environment:
      - APACHE_HTTP_PORT_NUMBER=80
      - APACHE_HTTPS_PORT_NUMBER=443
      - PRESTASHOP_HOST=www.*******.net
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_NAME=prestashop
      - PRESTASHOP_DATABASE_USER=test2020
      - PRESTASHOP_DATABASE_PASSWORD=test2020
      - ALLOW_EMPTY_PASSWORD=no
      - PRESTASHOP_COUNTRY=it      
      - PRESTASHOP_EMAIL=test@test.com
      - PRESTASHOP_PASSWORD=testP
      - PRESTASHOP_FIRST_NAME=testU
      - PRESTASHOP_LAST_NAME=testL
      - NAMI_DEBUG=--log-level=trace  
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /certs:/certs
      - prestashop_app:/bitnami
      
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  prestashop_app:
    driver: local
```

**Describe the results you received:**

Console output:
```
Starting bitnami_mariadb_1 ... done
Starting bitnami_prestashop_1 ... done
Attaching to bitnami_mariadb_1, bitnami_prestashop_1
mariadb_1     | mariadb 15:35:49.28
mariadb_1     | mariadb 15:35:49.28 Welcome to the Bitnami mariadb container
mariadb_1     | mariadb 15:35:49.29 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1     | mariadb 15:35:49.29 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1     | mariadb 15:35:49.29
prestashop_1  | app-entrypoint.sh 15:35:50.13
mariadb_1     | mariadb 15:35:49.29 INFO  ==> ** Starting MariaDB setup **
mariadb_1     | mariadb 15:35:49.40 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
prestashop_1  | app-entrypoint.sh 15:35:50.13 Welcome to the Bitnami prestashop container
prestashop_1  | app-entrypoint.sh 15:35:50.13 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-prestashop
mariadb_1     | mariadb 15:35:49.41 INFO  ==> Initializing mariadb database
mariadb_1     | mariadb 15:35:49.44 INFO  ==> Using persisted data
mariadb_1     | mariadb 15:35:49.46 INFO  ==> Running mysql_upgrade
mariadb_1     | mariadb 15:35:49.46 INFO  ==> Starting mariadb in background
prestashop_1  | app-entrypoint.sh 15:35:50.14 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-prestashop/issues
prestashop_1  | app-entrypoint.sh 15:35:50.14
prestashop_1  | app-entrypoint.sh 15:35:50.14 INFO  ==> Mounting certificates files from /certs...
mariadb_1     | mariadb 15:35:50.92 INFO  ==> Stopping mariadb
mariadb_1     | mariadb 15:35:52.93 INFO  ==> ** MariaDB setup finished! **
mariadb_1     |
mariadb_1     | mariadb 15:35:53.04 INFO  ==> ** Starting MariaDB **
mariadb_1     | 2020-05-02 15:35:53 140012307779392 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.44-MariaDB) starting as process 1 ...
mariadb_1     | 2020-05-02 15:35:53 140012307779392 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.
mariadb_1     |
mariadb_1     | 2020-05-02 15:35:53 140012307779392 [Note] InnoDB: Using mutexes to ref count buffer pool pages
mariadb_1     | 2020-05-02 15:35:53 140012307779392 [Note] InnoDB: The InnoDB memory heap is disabled
mariadb_1     | 2020-05-02 15:35:53 140012307779392 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1     | 2020-05-02 15:35:53 140012307779392 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mariadb_1     | 2020-05-02 15:35:53 140012307779392 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1     | 2020-05-02 15:35:53 140012307779392 [Note] InnoDB: Using Linux native AIO
mariadb_1     | 2020-05-02 15:35:53 140012307779392 [Note] InnoDB: Using SSE crc32 instructions
mariadb_1     | 2020-05-02 15:35:53 140012307779392 [Note] InnoDB: Initializing buffer pool, size = 128.0M
mariadb_1     | 2020-05-02 15:35:53 140012307779392 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1     | 2020-05-02 15:35:53 140012307779392 [Note] InnoDB: Highest supported file format is Barracuda.
mariadb_1     | 2020-05-02 15:35:53 140012307779392 [Note] InnoDB: 128 rollback segment(s) are active.
mariadb_1     | 2020-05-02 15:35:53 140012307779392 [Note] InnoDB: Waiting for purge to start
mariadb_1     | 2020-05-02 15:35:53 140012307779392 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.46-86.2 started; log sequence number 10064828
mariadb_1     | 2020-05-02 15:35:53 140012307779392 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1     | 2020-05-02 15:35:53 140011422873344 [Note] InnoDB: Dumping buffer pool(s) not yet started
mariadb_1     | 2020-05-02 15:35:53 140012307779392 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_1     | 2020-05-02 15:35:53 140012307779392 [Warning] 'proxies_priv' entry '@% root@adc4c8c28faa' ignored in --skip-name-resolve mode.
mariadb_1     | 2020-05-02 15:35:53 140012307779392 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1     | Version: '10.1.44-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
prestashop_1  | nami    INFO  Initializing prestashop
prestashop_1  | apache  TRACE Skipping reload: com.bitnami.apache not running
prestashop_1  | apache  TRACE [runProgram] Executing: null /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
prestashop_1  | Error executing 'postInstallation': "size" argument must not be negative
prestashop_1  | nami    TRACE RangeError: Error executing 'postInstallation': "size" argument must not be negative
prestashop_1  |     at Function.Buffer.alloc (buffer.js:233:3)
prestashop_1  |     at new Buffer (buffer.js:156:19)
prestashop_1  |     at FileReader.read (/opt/bitnami/nami/node_modules/nami-utils/lib/file/FileReader.js:53:20)
prestashop_1  |     at Service._execServiceCommand (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:151:50)
prestashop_1  |     at Service._start (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:348:12)
prestashop_1  |     at Service.start (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:376:30)
prestashop_1  |     at Service.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:51:276)
prestashop_1  |     at Object.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:51:276)
prestashop_1  |     at ApacheHandler.start (/root/.nami/components/com.bitnami.prestashop/lib/handlers/webservers/apache/index.js:66:23)
prestashop_1  |     at Component.$app.postInstallation (/root/.nami/components/com.bitnami.prestashop/main.js:19:20)
bitnami_prestashop_1 exited with code 1

```

**Describe the results you expected:**

The HTTPs connection working with the correct certificate.

**Additional information you deem important (e.g. issue happens only occasionally):**

This issue happens everytime if I provide the certs from an external volume.

**Version**

- Output of `docker version`: 

```
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:26:00 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:04:38 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~19.10.2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 5
  Paused: 0
  Stopped: 2
 Images: 44
 Server Version: 19.03.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-46-generic
 Operating System: Ubuntu 19.10
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.775GiB
 Name: vmi373693.contaboserver.net
 ID: JNFO:LQUT:YKZG:S4Z2:X2A5:P5BX:VP4E:XVMR:GBAM:GK7U:FAM3:DP3I
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

```
