### ISSUE TITLE
The readme section: 'Upgrading Prestashop'   don't upgrade prestashop 

### ISSUE THREAD

**Issue by Nittarab** [bitnami/bitnami-docker-prestashop#89]
**Description**

If you follow the readme section: "Upgrading Prestashop". You get an updated container with the old version of Prestashop. 

If there is a way to automate the prestashop upgrade during the container upgrade is cool. 
Otherway the readme section title is not correct and it is deceiving

*Step to reproduce*

I used this docker-compose file:
```
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  prestashop:
    image: 'bitnami/prestashop:1.7.6-3-debian-10-r21'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'prestashop_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
```

1. `docker-compose up`
2. `docker-compose stop prestashop`
3. I change the tag in the docker compose  `image: 'bitnami/prestashop:1.7.6-5-debian-10-r27'`
4. `docker-compose rm -v prestashop`
5. `docker-compose up prestashop`

Prestashop version still 1.7.6.3

**Comment by miguelaeh** [comment]
Hi @Nittarab, 
Could you share the steps you followed and the versions you are expecting?
Did you upgrade Prestashop manually in a running container before follow the upgrade section in the README?

**Comment by Nittarab** [comment]
Hi  @miguelaeh,  
I update the issue with the steps I made. I just login to the backoffice, I haven't done any actions

**Comment by miguelaeh** [comment]
Hi @Nittarab ,
I was able to follow your steps and Prestashop was properly updated. Should it be possible that you have some volumes persisted? I would try to execute `docker-compose down -v`, also you can change to other directory and copy the docker-compose again so you ensure that there are not wrong volumes.

**Comment by Nittarab** [comment]
Hi @miguelaeh,
if you remove the volume you also remove all the application data :sweat_smile:  

I think we should be able to update Prestashop in the same pvc. I know this is not the correct design of a docker application.  But if you provide support in my opinion the container should also be able to update the Prestashop version

**Comment by miguelaeh** [comment]
Hi @Nittarab ,
> if you remove the volume you also remove all the application data

Yep, that is true, I supposed you were using that docker-compose only for debug.
Running a fresh instance I am able to upgrade it, that is why I think it should be due to some wrong configuration stored. Following your steps one by one in a fresh installation you should be able to upgrade it. Could you share the changes you performed before the upgrade? I think you should be able to back up the data folder, deploy the new version, and copy the data folder. That is not ideal, but I think it could work as a workaround.

**Comment by Nittarab** [comment]
Hi @miguelaeh, 
Yes, I'm using docker-compose just for debug. But I have a thousand shops in production, I'm using helm and my docker image is a fork this repo. 
Prestashop store data in volumes ad of course in databases, as you know the user can install modules themes and other stuff. 

If you have a shop running for example in version 1.7.4.4 (base on bitnami image) and you would update the Prestashop version without losing any data you can:
1. Update te Prestashop from the BackOffice using 1clickupgrade module, but this is not an automatic solution and can't be under control. Olso your docker images will remain an old image based on a deprecated minideb.
2. Write a custom script that upgrades Prestashop version when docker image point to a new Prestashop version 

If I'm wrong and we can update the Prestashop version just updating the docker image. I'm so happy. Otherwise, I think is incorrect the title of readme section.

**Comment by miguelaeh** [comment]
Hi @Nittarab ,
I a bit confused right now, the upgrade section seems to be correct, following the steps you posted it is also updated as expected. That is point number 2 in your previous comment.
Were you able to update your containers? Did you find any issue upgrading them?

**Comment by Nittarab** [comment]
Hi @miguelaeh, 
I was able to upgrade the container and Prestashop but, to do that I written a custom script that download the new Prestashop version, update files, modules, run the upgrade in the database etc.

A normal contaier upgrade dont't upgrade the prestashop version

**Comment by miguelaeh** [comment]
Hi @Nittarab ,
Could you test those steps again, please? I cannot reproduce what you are reporting, following the steps you posted it is perfectly updated.

**Comment by Nittarab** [comment]
Sorry for my late reply, 
I try again to update the Prestashop version by updating the container.

1th docker-compose
```
version: '2'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.1-debian-10'
    environment:
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  prestashop:
    image: 'docker.io/bitnami/prestashop:1.7.6-3-debian-10-r21'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'prestashop_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
```

cmd:
`docker-compose up`

The container startup successfully with prestashop at versione 1.7.6.3
![image](https://user-images.githubusercontent.com/6181406/87018260-4baa5080-c1d1-11ea-8a59-ea8e4182bb9f.png)



cmd:
`docker-compose stop`


I change the image tag in the docker-compose.yaml:
```
  prestashop:
    image: 'docker.io/bitnami/prestashop:1.7-debian-10'
```

cmd:
`docker-compose up`

Logs
```
mariadb_1     | mariadb 08:48:58.97 
mariadb_1     | mariadb 08:48:58.98 Welcome to the Bitnami mariadb container
prestashop_1  | 
mariadb_1     | mariadb 08:48:58.98 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
prestashop_1  | Welcome to the Bitnami prestashop container
mariadb_1     | mariadb 08:48:58.99 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
prestashop_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-prestashop
mariadb_1     | mariadb 08:48:58.99 
mariadb_1     | mariadb 08:48:58.99 INFO  ==> ** Starting MariaDB setup **
prestashop_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-prestashop/issues
mariadb_1     | mariadb 08:48:59.03 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
prestashop_1  | 
mariadb_1     | mariadb 08:48:59.04 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
prestashop_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1     | mariadb 08:48:59.08 INFO  ==> Initializing mariadb database
mariadb_1     | mariadb 08:48:59.26 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb_1     | mariadb 08:48:59.35 INFO  ==> Setting user option
mariadb_1     | mariadb 08:48:59.90 INFO  ==> Using persisted data
mariadb_1     | mariadb 08:49:00.10 INFO  ==> Running mysql_upgrade
mariadb_1     | mariadb 08:49:00.15 INFO  ==> Starting mariadb in background
mariadb_1     | mariadb 08:49:02.21 INFO  ==> Stopping mariadb
prestashop_1  | nami    INFO  Initializing php
prestashop_1  | nami    INFO  php successfully initialized
mariadb_1     | mariadb 08:49:05.22 INFO  ==> ** MariaDB setup finished! **
mariadb_1     | 
mariadb_1     | mariadb 08:49:05.28 INFO  ==> ** Starting MariaDB **
mariadb_1     | 2020-07-09  8:49:05 139838367858496 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.45-MariaDB) starting as process 1 ...
mariadb_1     | 2020-07-09  8:49:05 139838367858496 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.
mariadb_1     | 
mariadb_1     | 2020-07-09  8:49:05 139838367858496 [Note] InnoDB: Using mutexes to ref count buffer pool pages
mariadb_1     | 2020-07-09  8:49:05 139838367858496 [Note] InnoDB: The InnoDB memory heap is disabled
mariadb_1     | 2020-07-09  8:49:05 139838367858496 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1     | 2020-07-09  8:49:05 139838367858496 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mariadb_1     | 2020-07-09  8:49:05 139838367858496 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1     | 2020-07-09  8:49:05 139838367858496 [Note] InnoDB: Using Linux native AIO
mariadb_1     | 2020-07-09  8:49:05 139838367858496 [Note] InnoDB: Using SSE crc32 instructions
mariadb_1     | 2020-07-09  8:49:05 139838367858496 [Note] InnoDB: Initializing buffer pool, size = 128.0M
mariadb_1     | 2020-07-09  8:49:05 139838367858496 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1     | 2020-07-09  8:49:05 139838367858496 [Note] InnoDB: Highest supported file format is Barracuda.
mariadb_1     | 2020-07-09  8:49:05 139838367858496 [Note] InnoDB: 128 rollback segment(s) are active.
mariadb_1     | 2020-07-09  8:49:05 139838367858496 [Note] InnoDB: Waiting for purge to start
mariadb_1     | 2020-07-09  8:49:05 139838367858496 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.47-87.0 started; log sequence number 10739221
mariadb_1     | 2020-07-09  8:49:05 139837485086464 [Note] InnoDB: Dumping buffer pool(s) not yet started
mariadb_1     | 2020-07-09  8:49:05 139838367858496 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1     | 2020-07-09  8:49:05 139838367858496 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_1     | 2020-07-09  8:49:05 139838367858496 [Warning] 'proxies_priv' entry '@% root@ec2f5cc0836e' ignored in --skip-name-resolve mode.
mariadb_1     | 2020-07-09  8:49:05 139838367858496 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1     | Version: '10.1.45-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
prestashop_1  | nami    INFO  Initializing apache
prestashop_1  | nami    INFO  apache successfully initialized
prestashop_1  | nami    INFO  Initializing mysql-client
prestashop_1  | nami    INFO  mysql-client successfully initialized
prestashop_1  | nami    INFO  Initializing prestashop
prestashop_1  | prestas INFO  Configuring webserver...
prestashop_1  | prestas INFO  Configuring PHP settings...
prestashop_1  | prestas INFO 
prestashop_1  | prestas INFO  ########################################################################
prestashop_1  | prestas INFO   Installation parameters for prestashop:
prestashop_1  | prestas INFO     Persisted data and properties have been restored.
prestashop_1  | prestas INFO     Any input specified will not take effect.
prestashop_1  | prestas INFO   This installation requires no credentials.
prestashop_1  | prestas INFO  ########################################################################
prestashop_1  | prestas INFO 
prestashop_1  | nami    INFO  prestashop successfully initialized
prestashop_1  | INFO  ==> Starting gosu... 
prestashop_1  | [Thu Jul 09 08:49:22.121490 2020] [ssl:warn] [pid 116] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
prestashop_1  | [Thu Jul 09 08:49:22.122434 2020] [ssl:warn] [pid 116] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
prestashop_1  | [Thu Jul 09 08:49:22.162835 2020] [ssl:warn] [pid 116] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
prestashop_1  | [Thu Jul 09 08:49:22.163181 2020] [ssl:warn] [pid 116] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name

```

I can't see any upgrade action in the Prestashop startup... In fact, if I go to the backend of Prestashop I see in the same version:
![image](https://user-images.githubusercontent.com/6181406/87019243-a6907780-c1d2-11ea-9da5-337d2d46ea93.png)
 

Of course, If I delete de volume the container will create a new one  with the new version of Prestashop. But If i delete the volume in production, I'll delete all the modules/images and the other stuff that Prestashop memorize in the filesystem.

I know that the pattern of Prestashop, Wordpress ecc doesn't fit good with the container.  But I think we should invest more time to create a new way to dockerize this application.
