### ISSUE TITLE
1.6.1.6 | localhost didn’t send any data ERR_EMPTY_RESPONSE | no error displayed

### ISSUE THREAD

**Issue by adrienpsl** [bitnami/bitnami-docker-prestashop#93]
hello :)

**Description**

I've trying to build an 1.6.1.6 shop, everything seems ok,  no error message
but when I tried to connect at localhost:80 I only get:

localhost didn’t send any data.
ERR_EMPTY_RESPONSE

**Steps to reproduce the issue:**
docker-compose:
```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.1'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_prestashop
      - MARIADB_DATABASE=bitnami_prestashop
    volumes:
      - ./db:/bitnami/mariadb
  prestashop:
    image: 'docker.io/bitnami/prestashop:1.6.1.6-r4'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - PRESTASHOP_HOST=localhost
      - PRESTASHOP_DATABASE_HOST=mariadb
      - PRESTASHOP_DATABASE_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=bn_prestashop
      - PRESTASHOP_DATABASE_NAME=bitnami_prestashop
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./prestashop:/bitnami/prestashop
    depends_on:
      - mariadb
```

the docker-compose build output:
```
prestashop_1  |   *** Welcome to the prestashop image ***
prestashop_1  |   *** Brought to you by Bitnami ***
prestashop_1  |   *** More information: https://github.com/bitnami/bitnami-docker-prestashop ***
prestashop_1  |   *** Issues: https://github.com/bitnami/bitnami-docker-prestashop/issues ***
```

**Describe the results you expected:**
**
localhost didn’t send any data.
ERR_EMPTY_RESPONSE 
**

and no connection log on prestashop image log

**Version**

- Output of `docker version`:
```
Docker version 19.03.13, build 4484c46d9d
```

I'm on Osx 10.15.7

thank you in advance :).
